[provider]
cluster = "localnet"
wallet = "/root/.config/solana/id.json"

[programs.localnet]
implementation_0 = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
implementation_1 = "7oMeM6mg429aeE9kJtskWNQmQU53tAFCtPzwQARUTF2h"
invocation = "65t8LH4Yp8ugymLYGYAeuQRJNJoqshkByEWJJktgpoUa"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
